"""empty message

Revision ID: 5c98e013b1dd
Revises: 
Create Date: 2019-07-10 10:07:17.715550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c98e013b1dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('Пол', sa.String(length=200), nullable=True),
    sa.Column('Предполагаемый возраст', sa.String(length=200), nullable=True),
    sa.Column('Страна проживания', sa.String(length=200), nullable=True),
    sa.Column('Профессия', sa.String(length=200), nullable=True),
    sa.Column('Категория занимаемой должности', sa.String(length=200), nullable=True),
    sa.Column('Ср.ост. по всем сч. за последн. 3 мес.', sa.Integer(), nullable=True),
    sa.Column('Семейное положение', sa.String(length=200), nullable=True),
    sa.Column('Дети', sa.String(length=200), nullable=True),
    sa.Column('Наличие жилья опред. типа', sa.String(length=200), nullable=True),
    sa.Column('Наличие хобби', sa.String(length=200), nullable=True),
    sa.Column('Владелец потреб. электрон.', sa.String(length=200), nullable=True),
    sa.Column('Интерес к потреб. электрон.', sa.String(length=200), nullable=True),
    sa.Column('Наличие автомобиля', sa.String(length=200), nullable=True),
    sa.Column('Владелец страхового продукта', sa.String(length=200), nullable=True),
    sa.Column('Интерес к страховому продукту', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
