"""empty message

Revision ID: 609abbac84b1
Revises: 
Create Date: 2019-07-09 12:08:16.381911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609abbac84b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('Пол', sa.String(length=200), nullable=True),
    sa.Column('Предполагаемый возраст', sa.String(length=200), nullable=True),
    sa.Column('Страна проживания', sa.String(length=200), nullable=True),
    sa.Column('Профессия', sa.String(length=200), nullable=True),
    sa.Column('Категория занимаемой должности', sa.String(length=200), nullable=True),
    sa.Column('Средний остаток по всем счетам за последние 3 месяца', sa.Integer(), nullable=True),
    sa.Column('Семейное положение', sa.String(length=200), nullable=True),
    sa.Column('Дети', sa.String(length=200), nullable=True),
    sa.Column('Наличие жилья определенного типа', sa.String(length=200), nullable=True),
    sa.Column('Наличие хобби', sa.String(length=200), nullable=True),
    sa.Column('Владелец потребительской электроники определенного типа', sa.String(length=200), nullable=True),
    sa.Column('Интерес к потребительской электронике определенного типа', sa.String(length=200), nullable=True),
    sa.Column('Наличие автомобиля', sa.String(length=200), nullable=True),
    sa.Column('Владелец страхового продукта', sa.String(length=200), nullable=True),
    sa.Column('Интерес к страховому продукту', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
